dubbo :  
  protocol :   
    prot : -1  
    name  : dubbo  
  application :   
    name : hello-world-app  
  registry :  
    address : zookeeper://192.168.1.175:2182
  packageName : org.bana.springboot.plugin.dubbo.provider.impl
  
server :  
  port : 8083 
  
debug : true